language: php

php:
  - 5.6
  - 7.0

branches:
  only:
    - master
    
install:
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar -O "$HOME/ocular.phar"
  
script:
  - php vendor/bin/codecept run --coverage --coverage-xml

after_success:
  - php "$HOME/ocular.phar" code-coverage:upload --format=php-clover tests/_output/coverage.xml

